
on:
  push:
    branches:
      - master
      - renovate/*
  pull_request:
    branches:
      - master

jobs:
  mypy:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
      with:
        python-version: "3.14"
    - run: pip install numpy mypy
    - run: sudo apt-get install libsuitesparse-dev libbtbb-dev liblapack-dev libcfitsio-dev libmetis-dev libgsl-dev
    # NB: force install to provisioned Python's PYTHONPATH
    - run: cmake -DPython_EXECUTABLE=$(which python) -DCMAKE_INSTALL_PREFIX=$(dirname $(dirname $(which pip))) && make pyphotospline && sudo make install
    - run: mypy test/*.py
  linux:
    runs-on: ubuntu-24.04
    needs: mypy
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.8
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install numpy scipy
      - run: sudo apt-get install libsuitesparse-dev libbtbb-dev liblapack-dev libcfitsio-dev libmetis-dev libgsl-dev
      - run: cmake -DPython_EXECUTABLE=$(which python) . && make && sudo make install
      - run: python -c "import photospline"
      - run: ctest --output-on-failure
  macos:
    runs-on: macos-15
    needs: linux
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.9
          - 3.12
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install numpy scipy
      - run: brew install suite-sparse cfitsio gsl
      - run: cmake -DPython_EXECUTABLE=$(which python) -DCMAKE_INSTALL_PREFIX=install . && make install
      - run: python -c "import photospline"
      - run: ctest --output-on-failure
  architecture-zoo:
    runs-on: ubuntu-24.04
    needs: linux
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu20.04
          - arch: ppc64le
            distro: ubuntu20.04
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: uraimo/run-on-arch-action@aa8e672a03e10b403401927ea2ceda57e1b68ac3 # v3
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          # cache install stage
          githubToken: ${{ github.token }}
          install: |
            apt-get update -q -y
            apt-get install -q -y cmake clang libsuitesparse-dev libbtbb-dev liblapack-dev libcfitsio-dev libmetis-dev libgsl-dev python3-dev python3-numpy python3-scipy
          run: |
            cmake -DPython_EXECUTABLE=$(which python3) .
            make
            make install
            python3 -c "import photospline"
            # ctest --output-on-failure


